### ISSUE TITLE
Error while initializing, [error pq: null value in column "currency_id" violates not-null constraint

### ISSUE THREAD

**Issue by twokaybee** [hexya-erp/hexya-base#1]
Hi,

   I am getting the following error while trying to start Hexya server for the very first time.

> pq: null value in column "currency_id" violates not-null constraint

 I did check the db and found the currency table and rate table both were empty. Could anyone help me on this. Detailed log attached.
[hexya.log](https://github.com/hexya-erp/hexya-base/files/1581826/hexya.log)

**Comment by npiganeau** [comment]
Hi,

Thanks for your interest in Hexya. 
The currency table should be populated when you run `hexya updatedb`.

Which hexya module did you import ?

**Comment by twokaybee** [comment]
Hi, thank you for your reply.

I actually followed the installation guidelines from http://hexya.io/docs/install/ 
In the steps provided, I checked out the demo project. But I skipped the step listed under 4.2 of the document. So, basically it's the demo project repository only.

**Comment by npiganeau** [comment]
Ok. I'll have a look. Actually there is a lot of ongoing work on hexya-base and hexya-addons to be abls to create a demo site in a few weeks and it is possible that the current "version" is broken.

You can also try to modify your DemoProject/config/project.go to import `github.com/hexya-erp/hexya-addons/account` instead of `sale`. Then drop your DB and run `hexya generate` `hexya updatedb` and `hexya server` again.

**Comment by twokaybee** [comment]
Ok, I will check and revert back after working on the modifications recommended. I would like to recommend creating branches and keeping the master always stable.

**Comment by twokaybee** [comment]
@npiganeau I tried the same what you mentioned in your previous comment and failed to load the same. Please check the ss.

![image](https://user-images.githubusercontent.com/32931985/34320901-fafb5a6e-e828-11e7-8623-fb70d8b5f07d.png)

**Comment by twokaybee** [comment]
Hi,

   Any update on this issue? If it will take time to resolve, I would be glad to know any work-around, such as providing a backup of a working database?

**Comment by npiganeau** [comment]
Hi,

I have several ongoing works, but right now it should work with the latest commits from all repos:
```
go get -u github.com/hexya-erp/hexya
go get -u -d github.com/hexya-erp/hexya-base
go get -u -d github.com/hexya-erp/hexya-addons
go get -u github.com/hexya-erp/hexya-demo
```
Then:
- drop your DB, and create it again.
- adapt "hexya.toml" in hexya-demo folder
- run `hexya generate` in hexya-demo folder
- run `hexya updatedb` in hexya-demo folder
- run `hexya server` in hexya-demo folder

Warning: modules are now defined in the hexya.toml config file. Install documentation has been updated, but make sure to clear cache in your browser if you read it from hexya.io. The demo project is updated too.

**Comment by inigofu** [comment]
I have tried with the new instructions several times and get the same when trying to start hexya server. I have seen that the updatedb proccess. also it says "Database updated sucessfully", during the process it gets the following error.
![image](https://user-images.githubusercontent.com/33458620/34848311-98950992-f71e-11e7-8e0d-7826e2e7dea2.png)

**Comment by npiganeau** [comment]
Sounds like both of you are running Windows while I'm on Linux. I'll have to try it. Which version of pg are you using?

**Comment by inigofu** [comment]
I'am using postgres 10.1

**Comment by twokaybee** [comment]
I am using 9.6

**Comment by twokaybee** [comment]
@npiganeau could you please share your dev env setup?

**Comment by npiganeau** [comment]
Ok, I found the pb. It had to do with the automatic call to `Init()` methods of models at bootstrap. I didn't see it on my side because I didn't drop my DB.

It's now fixed. Please let me know if it is OK for you so that I can close the issue.

**Comment by npiganeau** [comment]
For the record my dev setup is:
- Ubuntu 16.04
- go 1.9 (really looking forward to go 1.10 and its build cache that will dramatically reduce Hexya startup time)
- postgres 9.5

**Comment by twokaybee** [comment]
Sure will have a look and let you know soon.

**Comment by twokaybee** [comment]
Hi @npiganeau , for me, the issue still persists on windows. I did checkout all the modules from scratch and tried. Please find attached log file.

**Comment by inigofu** [comment]
I am also getting the same error.

**Comment by npiganeau** [comment]
@twokaybee sorry, I don't see your log

**Comment by inigofu** [comment]
I have been debuging and the problema seems to be that the csv file with currency data in base module are not loaded to database. So in line 61 of the 000hexya.go file "euro := pool.Currency().Search(env, pool.Currency().HexyaExternalID().Equals("base_EUR"))" it tries to find the euro it gets a null value and in the next sentence in creates a company with null currency.

How do we impor the csv?

**Comment by twokaybee** [comment]
Sorry for the mistake, please find attached.
[hexya_new.log](https://github.com/hexya-erp/hexya-base/files/1643773/hexya_new.log)

**Comment by npiganeau** [comment]
CSV should have been imported by `hexya updatedb`. Don't hesitate to drop DB before (and recreate) since updatedb is not fully reliable on db updates.

I'll have a look too.

**Comment by npiganeau** [comment]
I guess it's something like the symlink that fails on Windows and I don't catch the error (shame on me !).

Try running `hexya updatedb` in an admin shell to see if it's a permission related issue.

**Comment by npiganeau** [comment]
Yes, that's it: on windows non-admin users are not allowed to create symlinks.

Here is what I did:
- I've changed the symlinking to be done in `hexya generate`, so it means that `hexya generate` must be done as admin on windows.
- `hexya updatedb` and `hexya server` do not need admin privileges anymore.

Can you pull the changes with `go get -u github.com/hexya-erp/hexya` and check please ?

**Comment by twokaybee** [comment]
Yes, will update you back.

**Comment by inigofu** [comment]
It work for me executing hexya updatedb as admin before the update. With the latest versión now when starting server I get "Unknown parent menu ID, [parentID sale_teams_menu_sale_config caller BootStrap]"

**Comment by npiganeau** [comment]
After you downloaded the new version, you need to run `hexya generate` (as admin) again before running `hexya server`.

After running `hexya generate` you should have inside `hexya/hexya/server` the following folders:
- data
- i18n
- resources
- static
- templates
- views

and inside each folder you should have symlinks to the folder of the same name in each package (e.g. `hexya/hexya/data/base` should be a symlink to `hexya-base/base/data`)

**Comment by npiganeau** [comment]
BTW to speed up hexya startup, you can run `go install ./...` inside the `hexya-erp/hexya` folder after you have run `hexya generate`. This will take a while, but following calls to `hexya updatedb` or `hexya server` should be much quicker.

This hack will no longer be necessary with go 1.10

**Comment by twokaybee** [comment]
@npiganeau  I am also having the same issue reported by @inigofu . Log file attached, below the listing of hexya/hexya/server.

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       19-01-2018     16:25                data
d-----       19-01-2018     16:25                i18n
d-----       19-01-2018     16:25                resources
d-----       19-01-2018     16:25                static
d-----       19-01-2018     16:25                templates
-a----       19-01-2018     16:24           2738 context.go
-a----       19-01-2018     16:24           4722 modules.go
-a----       19-01-2018     16:24           4270 routes.go
-a----       19-01-2018     16:24           3895 server.go
```
The views folder is missing from server folder and is present in hexya/hexya/. However, the titled issue '"error pq: null value in column "currency_id"' is fixed.
[hexya_190118.log](https://github.com/hexya-erp/hexya-base/files/1646535/hexya_190118.log)

**Comment by npiganeau** [comment]
Indeed, the views folder was missing from my list.

Can you try again now ? Update hexya and run `hexya generate` again and check that you have the views folder.

**Comment by npiganeau** [comment]
My mistake, there shouldn't be a views folder, so that's OK.

Problem is that saleTeams/resources folder is not symlinked. I'll check why.

**Comment by npiganeau** [comment]
It should work now (hopefully...). Update hexya and run `hexya generate` again. You should have a subfolder `saleTeams` inside the `resources` dir.

**Comment by inigofu** [comment]
Now is working. Thanks.

**Comment by twokaybee** [comment]
Hi @npiganeau , now its working fine. Thanks for your support.

**Comment by npiganeau** [comment]
Thanks for your feedback
