### ISSUE TITLE
will you use the VUE or Polymer  as UI framework?

### ISSUE THREAD

**Issue by hzmsrv** [hexya-erp/hexya-base#4]
will you use the VUE or Polymer  as UI framework?

**Comment by npiganeau** [comment]
As the standard UI, we use Odoo's client which uses its own framework (see web module), for two main reasons:
1. It has already many features and was easy to interface with Hexya server
2. It is modular, the same way as the server, which is the no.1 feature we want for Hexya

We don't have plans for the short or mid-term to replace it.
